"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
type Order={id:string;created_at:string;name:string;phone:string;method:string;neighborhood:string|null;address:string|null;notes:string|null;items_json:string;burger_count:number;subtotal:number;delivery_fee:number|null;total:number|null;status:string;paid_at:string|null;payment_mode:string|null;refund_note:string|null};
type AdminData={orders:Order[];settings:{capacity:number;paused:boolean};paid:number;demo:boolean;error?:string};
const money=(n:number)=>(n/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const labels:Record<string,string>={awaiting_quote:"Aguardando taxa",ready_for_payment:"Aguardando Pix",awaiting_payment:"Aguardando Pix",paid:"Pago",preparing:"Em preparo",ready:"Pronto",out_for_delivery:"Saiu para entrega",completed:"Concluído",refunded:"Devolução registrada"};
const names:Record<string,string>={classic:"Clássico",bacon:"Bacon","fries-small":"Batata pequena","fries-large":"Batata grande",water:"Água mineral",coke:"Coca-Cola","coke-zero":"Coca-Cola Zero"};
export default function AdminDashboard(){
  const [data,setData]=useState<AdminData|null>(null);
  const [capacity,setCapacity]=useState(100);
  const [error,setError]=useState("");
  const [password,setPassword]=useState("");
  const [feeInputs,setFeeInputs]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{const r=await fetch("/api/admin");const x=await r.json() as AdminData;if(!r.ok)throw new Error(x.error||"Acesso restrito.");setData(x);setCapacity(x.settings.capacity);},[]);
  useEffect(()=>{const initial=setTimeout(()=>load().catch(e=>setError(e.message)),0);const timer=setInterval(()=>load().catch(()=>{}),10000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load]);
  const paidOrders=data?.orders.filter(o=>o.paid_at&&o.status!=="refunded")??[];
  const revenue=paidOrders.reduce((s,o)=>s+(o.total??0),0);
  const pendingQuotes=data?.orders.filter(o=>o.status==="awaiting_quote").length??0;
  const paidPosition=new Map<string,{start:number;end:number}>();
  let running=0;
  for(const order of [...paidOrders].sort((a,b)=>(a.paid_at||"").localeCompare(b.paid_at||""))){
    const start=running+1; running+=order.burger_count;
    paidPosition.set(order.id,{start,end:running});
  }
  async function changeSettings(next:{capacity:number;paused:boolean}){setError("");const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});const x=await r.json() as {error?:string};if(!r.ok){setError(x.error||"Falha ao salvar.");return;}await load();}
  async function orderAction(id:string,body:Record<string,unknown>){setError("");const r=await fetch(`/api/admin/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json() as {error?:string};if(!r.ok){setError(x.error||"Falha ao atualizar.");return;}await load();}
  async function login(event:React.FormEvent){event.preventDefault();setError("");const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const x=await r.json() as {error?:string};if(!r.ok){setError(x.error||"Acesso negado.");return;}setPassword("");await load();}
  const over=Math.max(0,(data?.paid??0)-(data?.settings.capacity??100));
  return <div className="admin-shell"><aside className="admin-side"><Link className="brand" href="/"><span className="brand-mark">B<span>.</span></span><span>BLUECKYARDIGANS</span></Link><nav className="side-nav"><a href="#visao-geral">Visão geral</a><a href="#pedidos">Pedidos</a><Link href="/">Ver loja</Link></nav><p className="side-foot">Painel da equipe · 29/10/2026</p></aside><main className="admin-main"><header className="admin-head"><div><p className="section-kicker">Painel da equipe</p><h1>Controle da noite</h1><p>Pedidos e pagamentos atualizados a cada 10 segundos.</p></div><Link href="/" target="_blank" rel="noreferrer">Abrir loja ↗</Link></header>
    {error&&<div className="admin-alert" role="alert">{error} {!data&&<a href="/signin-with-chatgpt?return_to=/admin" target="_top">Entrar com ChatGPT</a>}</div>}
    {!data&&<form className="admin-panel" onSubmit={login}><h2>Acesso da equipe</h2><p>Entre com a senha do painel ou com sua conta autorizada do Site privado.</p><div className="admin-controls"><input type="password" aria-label="Senha do painel" placeholder="Senha do painel" value={password} onChange={e=>setPassword(e.target.value)}/><button type="submit">Entrar</button></div></form>}
    {data&&<><section id="visao-geral" className="metric-grid"><div className={`metric ${data.paid>=data.settings.capacity?"warning":""}`}><span>Hambúrgueres pagos</span><strong>{data.paid} <small>/ {data.settings.capacity}</small></strong><div className="progress-track"><div style={{width:`${Math.min(100,data.paid/data.settings.capacity*100)}%`}}/></div></div><div className="metric"><span>Pedidos pagos</span><strong>{paidOrders.length}</strong><small>{pendingQuotes} aguardando taxa</small></div><div className="metric"><span>Total recebido</span><strong style={{fontSize:37}}>{money(revenue)}</strong><small>Exclui devoluções registradas</small></div></section>
    {data.paid>=data.settings.capacity&&<div className="admin-alert">A marca de {data.settings.capacity} hambúrgueres foi atingida. As vendas continuam abertas. Revise os pedidos excedentes, aumente a capacidade ou pause novas compras.</div>}
    {over>0&&<div className="admin-alert">{over} hambúrguer{over===1?"":"es"} acima da capacidade atual. Considere a ordem de confirmação do pagamento para decidir atendimento e devoluções.</div>}
    {data.demo&&<div className="admin-alert">Modo de demonstração. Os botões de simular pagamento não movimentam dinheiro.</div>}
    <section className="admin-panel"><h2>Controle de vagas</h2><div className="admin-controls"><label htmlFor="capacity">Capacidade de hambúrgueres</label><input id="capacity" type="number" min="1" max="10000" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/><button onClick={()=>changeSettings({capacity,paused:data.settings.paused})}>Salvar capacidade</button><button className="secondary" onClick={()=>changeSettings({capacity:data.settings.capacity,paused:!data.settings.paused})}>{data.settings.paused?"Reabrir pedidos":"Pausar pedidos"}</button></div><p style={{fontSize:12,color:"#6c7b98",marginBottom:0}}>Para liberar novas vagas, aumente a capacidade e salve. Devoluções registradas saem do contador.</p></section>
    <section className="admin-panel" id="pedidos"><h2>Pedidos ({data.orders.length})</h2><div className="admin-orders">{data.orders.length===0&&<p>Os pedidos aparecerão aqui assim que alguém finalizar o formulário.</p>}{data.orders.map(o=><article className="admin-order" key={o.id}><div className="admin-order-top"><div><h3>{o.name} <small>#{o.id.slice(0,8).toUpperCase()}</small></h3><small>{new Date(o.created_at).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})} · {o.phone}</small></div><span className="status-pill">{labels[o.status]||o.status}</span></div><p>{(JSON.parse(o.items_json) as {id:string;quantity:number}[]).map(i=>`${i.quantity}× ${names[i.id]}`).join(" · ")}<br/>{o.method==="delivery"?`Entrega · ${o.address} · ${o.neighborhood}`:"Retirada na paróquia"} · Total: {o.total===null?"A definir":money(o.total)}{o.notes?<><br/>Obs.: {o.notes}</>:null}{paidPosition.has(o.id)&&<><br/>Prioridade pelo pagamento: hambúrgueres {paidPosition.get(o.id)!.start}–{paidPosition.get(o.id)!.end}{paidPosition.get(o.id)!.end>data.settings.capacity?" · acima da capacidade":""}</>}</p><div className="admin-order-actions">{o.status==="awaiting_quote"&&<><input aria-label="Taxa de entrega em reais" type="number" min="0" max="100" step=".01" placeholder="Taxa em R$" value={feeInputs[o.id]??""} onChange={e=>setFeeInputs(v=>({...v,[o.id]:e.target.value}))}/><button className="mini-button" onClick={()=>orderAction(o.id,{action:"quote",fee:Math.round(Number(feeInputs[o.id])*100)})}>Definir taxa</button></>}{data.demo&&o.total!==null&&!o.paid_at&&<button className="mini-button" onClick={()=>orderAction(o.id,{action:"demo_paid"})}>Simular pagamento</button>}{o.paid_at&&o.status!=="refunded"&&<><select aria-label="Atualizar situação" value={o.status} onChange={e=>orderAction(o.id,{action:"status",status:e.target.value})}><option value="paid">Pago</option><option value="preparing">Em preparo</option><option value="ready">Pronto</option><option value="out_for_delivery">Saiu para entrega</option><option value="completed">Concluído</option></select><button className="mini-button secondary" onClick={()=>{const note=window.prompt("Depois de devolver o valor fora do sistema, registre aqui o motivo ou referência da devolução:");if(note)orderAction(o.id,{action:"refund",note});}}>Registrar devolução</button></>}{o.refund_note&&<small>Devolução: {o.refund_note}</small>}<a className="mini-button secondary" href={`/pedido/${o.id}`} target="_blank" rel="noreferrer">Ver pedido</a></div></article>)}</div></section></>}
  </main></div>;
}
